### ISSUE TITLE
className prefix is not applied when removing "no-js" classname

### ISSUE THREAD

**Issue by keeganstreet** [Modernizr/Modernizr#1031]
The className prefix option is used to prefix the default Modernizr classnames. I am using a prefix of "supports", so I have classes like "supports-js", "supports-no-js", "supports-flexbox" and "supports-no-touch" for my feature detection classnames.

I have added a classname of "supports-no-js" to my HTML element, but Modernizr does not remove this. Modernizr has been hardcoded to remove a classname of "no-js" only, disregarding the className prefix option:

`docElement.className = docElement.className.replace(/(^|\s)no-js(\s|$)/, '$1$2') +`

This is a feature request to apply the className prefix option when removing the "no-js" className.

**Comment by BB-000** [comment]
When using Modenizr with a class prefix, .no-js was not getting removed. I could fix it by adding the correct prefix to .no-js in my html, however I wanted it to retain its original behaviour, and have either .no-js or .js class on the html (mainly because some third party libraries make use of these classes)

So I replaced 
{var r=new RegExp("(^|\\s)"+n+"no-js(\\s|$)");t=t.replace(r,"$1"+n+"js$2")}
with
{var r=new RegExp("(^|\\s)"+"no-js(\\s|$)");t=t.replace(r,"$1"+"js$2")}
