### ISSUE TITLE
Modernizr.preload doesn't actually check whether preload is supported

### ISSUE THREAD

**Issue by saebekassebil** [Modernizr/Modernizr#1085]
The `Modernizr.preload` test just checks whether the `preload` attribute is defined in a newly created `HTMLAudioElement`. The problem with this is, that it returns `true` for iOS devices, though it isn't supported/respected by Safari for iOS.

I wouldn't mind writing a proper test, but only if that's what you actually wants - as it stands now, the `Modernizr.preload` isn't actually useful for anything, since you cannot rely on it.

A proper test would be something like this:
http://jsbin.com/ehukaPe/4/edit

Works in Chrome, Safari, Firefox, etc., but fails on iOS devices (as far as I'm aware).

Let me know what you think,
cheers

**Comment by fonziemedia** [comment]
Hi, is this detection issue not going to be fixed? Seem quite straight forward to fix with saebekassebil suggestion, not sure why it's still open after almost 2 years. I've installed modernizr mainly for this to fix my audio pre-loader on iOS but 'Modernizr.audiopreload' is returning true on Safari iOS.. :(

If you could provide an update on your plans regarding this issue I would appreciate it. Meanwhile, I'll use something like saebekassebil's check suggestion.

Thanks!

**Comment by ryanseddon** [comment]
@fonziemedia we do this in our free time if you would like to see something fixed and it's "straight forward to fix" then you have the power to solve it, submit a PR help us out. We can only get better if people help build this with us.

**Comment by fonziemedia** [comment]
Hi ryanseddon, I've just re-read my previous comment and I do sound a bit like jerk but it wasn't my intention, honest. I've been reading through this project's documentation and Modernizr is a great tool, I'll be happy to help in anyway I can. I'm going to try to implement this test on my project and will post the results. I'm not familiar with Modernizr source code but will have a look and see if I can contribute. Thanks and apologies again if I came across a bit rude.

**Comment by ryanseddon** [comment]
@fonziemedia no worries! If you need any help please ask more than happy to assist you in landing some code in Modernizr!

**Comment by fonziemedia** [comment]
@ryanseddon thanks for offering some guidance, I'm definitely going to need it. I've cloned mordernizr and have set it up locally. I'm a bit of a noob with npm and grunt but I think I got it to work by following the readme.md instructions. However I did have to remove the first dependency: "@alrra/travis-scripts": "1.1.1" as it was spitting out an error, something like "package not found in npm". Not sure if this is essential though?

I've now been studying modernizr a bit and I think I have an idea of what's going on. I believe the current test is looking for the 'preload' value in the audio element which always returns a string  (auto/metadata/none) and thus will always return true. But please correct me if I'm wrong.

In regards to fixing this test, @saebekassebil and @patrickkettner kind of provided the solution. I was thinking of using the auto play test as a template, tweak it for purpose and use the loadeddata listener to return true or false. I've tested this with my own code but it's slow like the auto play.. it requires 0.3 sec or maybe more to be perfectly accurate (does modernizr have a standard limit for this kind of stuff?). I had faster results with the loadedmetadata listener which triggers before loadeddata but don't think I should use it as it can be misleading. I haven't tested thoroughly though (I don't have an iPhone and using xCode's emulator which is a bit of a pain) but please let me know what you think.

Also, not sure if this is the right place to post my progress and seek support? Let me know if I should be posting somewhere else.

Cheers!

**Comment by patrickkettner** [comment]
> However I did have to remove the first dependency: "@alrra/travis-scripts": "1.1.1" as it was spitting out an error, something like "package not found in npm". 

that means you have an old version of npm. It isn't essential for this, however you should update it in general. `npm update -g npm`

> Not sure if this is essential though?

not for what you are doing, nope :]

> I believe the current test is looking for the 'preload' value in the audio element which always returns a string (auto/metadata/none) and thus will always return true. But please correct me if I'm wrong.

close! the only bit off is the "always return a string". It is actually a bool. you can see what I mean by changing "preload" to "fonziemedia" (e.g. `"fonziemedia" in document.createElement("audio")`). It'll be `false`. If you do something that DOES exist (list `preload` in most modern desktop browsers), it'll be true. 

>(does modernizr have a standard limit for this kind of stuff?).

nope

> I had faster results with the loadedmetadata listener which triggers before loadeddata but don't think I should use it as it can be misleading. I haven't tested thoroughly though (I don't have an iPhone and using xCode's emulator which is a bit of a pain) but please let me know what you think.

sounds like something worth exploring!

> Also, not sure if this is the right place to post my progress and seek support? Let me know if I should be posting somewhere else.

here is great!

**Comment by fonziemedia** [comment]
Thanks for the quick reply @patrickkettner that's really helpful and makes total sense. Going to give it a go in the next few days and will keep you updated. Cheers!

**Comment by fonziemedia** [comment]
Hi @patrickkettner, I think I've got some code working for the audio preload test:

I'm using 'loadeddata' and it's taking up to 2.5 sec on safari to get a 1/20 reliability rate (shall I keep increasing the timeout or is this acceptable?). The problem is that the event listener can be really slow on Safari desktop the first time the page is loaded.. If the user refreshes the page the test is almost instant even with disabled caches (I reckon it's something to do with how Safari cache works).

On my previous post I mentioned 'loadedmetadata' but this returns true on iOS, I must have had cached code on Emulator when I first tried it.. I've also tested pretty much every progress event listener out there and results are either similar or they don't work. 

In regards to the audio test clip, I'm using the data:audio/mpeg;base64 uri which @saebekassebil used on his jsbin code, this is a 5 second silent mp3. I'm yet to add checks for other file types: m4a, ogg, wav etc. and this might bring better results? not sure.. Are there any rules on how to create these base64 uri's? I was thinking of recording some low quality silent audio and converting it to base64 using an online converter. Also, would it be a good idea to reduce this to a 3 sec or even shorter audio clip to reduce the amount of code required?

I'll be submitting a pull request soon. Let me know if there's any stuff I should take in consideration before doing so.

Cheers!

**Comment by patrickkettner** [comment]
a large part of that two seconds is almost certainly parsing a five second long audio clip. that event should fire the moment it starts playing, so try reducing it down heavily - like several dozen milliseconds.

rather than recording anything, I would use something like audacity to create a blank audio file of N length, and the highest compression.

**Comment by fonziemedia** [comment]
Hi @patrickkettner, I followed your advice and got better results: I'm now getting a reliable test with a 1400ms timeout.

I've tried using a blank audio file but it seems that most browsers won't load blank audio and the minimum clip length for Safari is around 75ms. So I've used the 'generate silence' feature in Audacity to create a 75ms mp3 (8kbps) and then converted it to a base64 data uri. Also tried using binary audio files but results were similar..

> that event should fire the moment it starts playing
This seems to be the case in Chrome and Firefox but Safari seems to behave differently when it comes to pre-loading data, not sure if on purpose or because it's slow..

I'm also having a bit of trouble on IE: I've noticed that the Cow tests throws an error (IE11) when the debugging console is up: SCRIPT445: Object doesn't support this action (File: eval code (109), Line: 218, Column: 7). Not sure if you're aware of this but it seems to be breaking my test.

Also, when adding some debugging console.log lines to my test I noticed some of the code runs twice and some even 3 times (VM/jquery?). Is this supposed to happen as part of the Cow tests?

**Comment by patrickkettner** [comment]
> Also, when adding some debugging console.log lines to my test I noticed some of the code runs twice and some even 3 times (VM/jquery?). Is this supposed to happen as part of the Cow tests?

yeah, we are testing inside of an iframe, an svg file, and with a dynamically provided window. 

I'll try to debug the IE 11 issues shortly

**Comment by fonziemedia** [comment]
Thanks for looking into it @patrickkettner . Not sure if I should've but I've been using a customised cow test to report on the audiopreload test result.

Good news is I've tried it in a custom test page using the Asinch API and it seems to be working flawlessly with a 300ms timeout, all major browsers working as expected including IE11!

Do you reckon it should be working with Cow tests too?

**Comment by patrickkettner** [comment]
yeah, it should be. you can PR what you have, if ya like

**Comment by fonziemedia** [comment]
Will do soon, just cleaning up some code and adding support for other audio file types. Cheers

**Comment by fonziemedia** [comment]
I've tried to submit a PR from my local branch to master but it says I haven't got permission, should I be submitting to a different branch?

**Comment by patrickkettner** [comment]
youll want to submit to your own fork

On Mon, Oct 5, 2015 at 4:23 PM, Fonziemedia <notifications@github.com>
wrote:

> I've tried to submit a PR from my local branch to master but it says I
> haven't got permission, should I be submitting to a different branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1085#issuecomment-145696826>
> .
>



-- 
patrick

**Comment by patrickkettner** [comment]
rather, push to your own fork, then PR that branch to our master

On Mon, Oct 5, 2015 at 4:24 PM, Patrick Kettner <patrickkettner@gmail.com>
wrote:

> youll want to submit to your own fork
>
> On Mon, Oct 5, 2015 at 4:23 PM, Fonziemedia <notifications@github.com>
> wrote:
>
>> I've tried to submit a PR from my local branch to master but it says I
>> haven't got permission, should I be submitting to a different branch?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Modernizr/Modernizr/issues/1085#issuecomment-145696826>
>> .
>>
>
>
>
> --
> patrick
>



-- 
patrick

**Comment by fonziemedia** [comment]
Got it, thanks! PR created

**Comment by patrickkettner** [comment]
fixes with  #1702
