### ISSUE TITLE
`inputtypes.number` returns true on Internet Explorer 11

### ISSUE THREAD

**Issue by ohcibi** [Modernizr/Modernizr#1376]
See this fiddle: http://jsfiddle.net/xajK9/

It alerts true on IE11 when it should alert false.

**Comment by stucox** [comment]
Reopening because of @aFarkas’ comments on https://github.com/patrickkettner/Modernizr/pull/5.

Mr Farkas is right: this version false-positives on Chrome & Firefox. Let’s continue the discussion there.

**Comment by patrickkettner** [comment]
merged in at 695fd5e

**Comment by vibetribe** [comment]
Excuse me, this problem is not fixed at all. on IE 11 it's still returning true.

**Comment by ohcibi** [comment]
The ignorance on this topic is dissatisfying. @patrickkettner could you please stop closing this issue when it is not solved at all? I mean we are not even close.

**Comment by patrickkettner** [comment]
what is the point of being a jerk?

**Comment by patrickkettner** [comment]
I just [downloaded Modernizr 3.3.1](https://modernizr.com/download?inputtypes) from the site, and it returns false in [ie 11](https://jsbin.com/fujazub/8)

in every
![image](https://cloud.githubusercontent.com/assets/465414/18742802/f37f6a9a-806a-11e6-8de6-4c659258b48a.png)

version
![image](https://cloud.githubusercontent.com/assets/465414/18742824/09d7a438-806b-11e6-9357-5422ea59f2e6.png)

available
![image](https://cloud.githubusercontent.com/assets/465414/18742833/16211f76-806b-11e6-8e1c-ddcc67b00267.png)


If you want to open up a new issue with information so that we can give you even more work for absolutely zero cost to you, please do.

If you want to continue to shit on said free work, please don't
