### ISSUE TITLE
blend-mode

### ISSUE THREAD

**Issue by yukulele** [Modernizr/Modernizr#1388]
add test to `background-blend-mode` and `mix-blend-mode` css properties.

**Comment by isaacwebfix** [comment]
For someone needing a solution for detecting background-blend-mode, this worked for me

```javascript
if(!('backgroundBlendMode' in document.body.style)) {
    // No support for background-blend-mode
  var html = document.getElementsByTagName("html")[0];
  html.className = html.className + " no-background-blend-mode";
}

**Comment by patrickkettner** [comment]
@isaacwebfix we landed a detect for this in master, that is more of less what you suggested

**Comment by dustindowell22** [comment]
I'm still having issues with `mix-blend-mode`. Could this ever be worked around??

**Comment by SndrL** [comment]
Having a project where I need to test for `mix-blend-mode` specifically. Hope this will get resolved one day :) If I'm correct this issue persists due to browser vendors?

**Comment by patrickkettner** [comment]
@dustindowell22 no, no detect has been created yet
@SndrL less the vendors fault as much as we just lack an API to accurately detect colors. You _might_ be able to render it inside of a `foreignObject` in an SVG element inside of canvas, then check the pixel value, but I have taken zero time to actually test that theory. It is a bit gross as it requires a number of other browser features to work in order to check.

**Comment by tedw** [comment]
One way you could test for support is by using `@supports`, as suggested here:
http://stackoverflow.com/a/28088291/673457

```css
@supports not (mix-blend-mode: multiply) {
  // fallback styles
}
```

This will work in most modern browsers, but not IE 11 or below:
http://caniuse.com/#feat=css-featurequeries

**Comment by strarsis** [comment]
Ironically IE11 and Edge don't support `background-blend-mode` – but also not `@supports`.
