### ISSUE TITLE
False detection of "cssvhunit" on iOS8 Safari (Portrait Mode)

### ISSUE THREAD

**Issue by codeofsumit** [Modernizr/Modernizr#1430]
Testing with iOS8 on an iPhone 5S.
Modernizr adds the "cssvhunit" class if the device is in landscape mode, but not for portrait mode.

viewport height as a unit was buggy prior to iOS8. It has been fixed now and works good in my testings.
The class should be added to the DOM in iOS8 Safari, regardless of device orientation.

**Comment by codeofsumit** [comment]
@michael-lynch there is currently no solution available afaik. We still use `vh-units` in our projects but IOS Safari will get a default px-value because modernizr still says viewport units aren't supported in portrait.

**Comment by patrickkettner** [comment]
I haven't had the opportunity to try it out but I believe if we modify the detect to include @scottjehl's [getViewportSize](https://gist.github.com/scottjehl/2051999), rather than use document.documentElement.clientHeight/Witdth, we may be able to fix this.

**Comment by anthwinter** [comment]
Hi, @patrickkettner was there any further investigation into using @scottjehl's getViewportSize? I have just discovered this issue in iOS9 Safari on iPhone 6+.

If I put `height: 100vh` on the body of the document I get a `getComputedStyle(document.body, null)['height']` result of 696px.
However, the `window.innerHeight` reports 628

If I use Scott's method, I get the–what seems to be correct–value of 628.

viewportsizes.com/mine/ also reports a viewport height of 628

**Comment by patrickkettner** [comment]
hey @anthwinter!

I was 99.999999999999% sure it would work perfectly (since @scottjehl is a damned genius), it was just a matter of implementing it. I just did in a branch.

Could @codeofsumit or you, @anthwinter (or anyone with an iOS 8 device - mine doesn't come for another day or two) test that branch to see if it is working for them?

**Comment by nhoizey** [comment]
Is this really fixed in current stable release?

I see Modernizr 3.1.0 on iOS 9.1 still reports `vh` support in landscape but not in portrait orientation.

FYI, it might not be the only platform where this is broken: http://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html
