### ISSUE TITLE
Modernizer w/ CommonJS (Browserify)

### ISSUE THREAD

**Issue by wesleytodd** [Modernizr/Modernizr#1431]
Due to the fact that Modernizr uses `this` as a reference to `window`, wrapping it in a closure breaks Modernizr.  

Is there a reason I don't know about for using `this` instead of window?  Because it certainly seems like this is a fickle practice with modern build systems.

**Comment by redoPop** [comment]
Just got caught by this. Here's where the issue lies in the latest stable release (2.8.3):

https://github.com/Modernizr/Modernizr/blob/v2.8.3/modernizr.js#L1406

This line has been in Modernizr since ~2011, and per @wesleytodd's comment it now seems to be making its way into 3.0.0. It was once used to shorten walks up the scope, [but `window` seems to work just as well for that](http://jsperf.com/this-vs-window-for-global-object-access).

Modernizr's assumption that `this === window` is causing it to break for an increasing number of us who use Browserify and similar tools. Wherever Modernizr's code is executed with a non-global function context, it will break. We can work around it by adding some extra steps to our build tools, but it could be avoided entirely by replacing the offending line with something like `})(window, document);`

**Comment by patrickkettner** [comment]
@redoPop PRs welcome!

**Comment by redoPop** [comment]
Awesome! Is `backport-fixes` the right branch to send pull requests to for Modernizr 2.8 fixes?

**Comment by patrickkettner** [comment]
we would want to land it in master before backporting it

**Comment by wesleytodd** [comment]
Pulled down the change in @redoPop's PR.  Confirmed that it works.  Thank!!  Closing.

**Comment by jeromecovington** [comment]
What version did this land in?

**Comment by redoPop** [comment]
The change [has been integrated into lib/build.js in master](https://github.com/Modernizr/Modernizr/blob/33a3721544eb191bf677d6337cd58fda9af0778e/lib/build.js#L30) for upcoming (3.x) versions. #1608 is the open PR for the backport to 2.x versions.

**Comment by mderrick** [comment]
I'm not entirely sure but I've still got a similar issue with this but only when building in the html5shiv because of [this line](https://github.com/Modernizr/Modernizr/blob/master/src/html5shiv.js#L331) and the html5printshiv because of [this line](https://github.com/Modernizr/Modernizr/blob/master/src/html5printshiv.js#L530).

If I change that to window everything works as expected. In my built file `this` is undefined at this point.

Would I be right in saying that this should also be updated?

**Comment by patrickkettner** [comment]
this was [changed](https://github.com/aFarkas/html5shiv/blob/master/dist/html5shiv.js#L326) in 3.7.3, we should update to that
