### ISSUE TITLE
Can we detect if video will be played in native player (many mobile devices, such as iPhone)?

### ISSUE THREAD

**Issue by DiegeticShadow** [Modernizr/Modernizr#1498]
On iPhone (perhaps all iOS devices) videos are displayed with a large “play” icon overlaid over them. Autoplaying video is disallowed, as is starting the video to play via JavaScript; only a user-initiated action can cause the video to play. Even then, though, on iPhone at least the video will play fullscreen in the iOS native player.

Is there some way to detect when we’re in an environment like this, where videos will play in an OS native player fullscreen, rather than inline?

**Comment by patrickkettner** [comment]
Nah :(

Sorry man

**Comment by DiegeticShadow** [comment]
Thanks for the quick response . . . care to explain why not’s not detectable? Having a video play inline versus play in an OS native player is a pretty major inconsistency between browsers. I know it’s by design, but it might drive the difference between designing a subpage to feature a video on its own page versus letting the user open it from a thumbnail to fullscreen using the native player.

I would think that this should at least be listed on the [Undetectables](https://github.com/Modernizr/Modernizr/wiki/Undetectables) page, ideally with an explanation for why it can’t be determined (or if maybe there was a bandwidth-intensive way to determine it, for example if we already have a `video` element on a page that we could work with).

**Comment by darcyclarke** [comment]
I believe this kind of broken video implementation is only found on iOS at this point. Detecting mobile Safari is probably your best bet here.

**Comment by patrickkettner** [comment]
@DiegeticShadow 
> care to explain why not’s not detectable?

With detections, we basically have two routes. 
1. Check for an API/via an API
2. Put something on the page and check the result.

Since there is no API that would say how the video will play, and the only way to actually test it would be to put a video on the page and then somehow see if it went fullscreen. The would also mean the end user would have to see a fullscreen video. Not something that is acceptable for modernizr.

> Having a video play inline versus play in an OS native player is a pretty major inconsistency between browsers

I know :[
Theres a bunch of features on mobile that are just not really possible to expose, outside of UA sniffing.

> I would think that this should at least be listed on the Undetectables page

Honestly, I think the reason it isn't there is because its _that_ big of a use case. I can't find a single other user on github or stackoverflow ever inquiring about this. 

> or if maybe there was a bandwidth-intensive way to determine it, for example if we already have a video element on a page that we could work with

We actually _do_ support autoplay detection in v3 of modernizr, which is the current master. We use a base64 encoded video and listen for some events, with a fallback to checking the current video time after a setTimeout.

**Comment by UdaySing** [comment]
@darcyclarke,
This issue is not only iOS, Couple of Android devices also having this kind of issue.

**Comment by viziionary** [comment]
@darcyclarke Actually it isn't just mobile safari. If I understand correctly, iPhone forces all browsers to use its special video player. I love Apple, but the fact that it cares so little for developers that it just throws away W3C specs on one of the most popular mobile devices on earth is really making me re-think my Apple love.

**Comment by bfred-it** [comment]
This is _sort of_ detectable but it involves:

- a touch event
- the video actually going fullscreen for a moment

The code is something like this:

```js
const supportsInlinePlayback = new Promise((resolve, reject) => {
    var video = document.createElement('video');
    video.src = '...';
    document.addEventListener('touchstart', () => video.play());
    
    // if this happens first, then it plays inline
    video.addEventListener('timeupdate', resolve);

    video.addEventListener('webkitbeginfullscreen', function() {
        video.webkitExitFullscreen();
        reject();
    });
})

supportsInlinePlayback.then(...yes...).catch(...no...)
```

Unforunately this is far from ideal, there doesn't seem to be a way to prevent the fullscreen animation from happening on the iPhone.
