### ISSUE TITLE
flexboxlegacy false positive safari mobile ios5

### ISSUE THREAD

**Issue by neonwired** [Modernizr/Modernizr#1602]
Safari mobile on iso5 gets flexboxlegacy but as far as i know it doesn't have flex support at all.

**Comment by patrickkettner** [comment]
[it does](http://caniuse.com/#search=flexbox)

**Comment by neonwired** [comment]
It only shows 7 & 8 support.

**Comment by patrickkettner** [comment]
![image](https://cloud.githubusercontent.com/assets/465414/7772819/6f17bf50-0055-11e5-9815-0158d4e7d1f7.png)

**Comment by neonwired** [comment]
Not sure where you're getting that from but http://caniuse.com/#search=flexbox doesnt currently show that, regardless it's not gospel and often inaccurate. It should be based on what happens in practice, you can get very very basic flex to work if you're lucky but it's generally far to inconsistent to of use.

Regardless there's is still a conflict on ios5 where modernizr reports both no-flexbox and flexboxlegacy at the same time, it can't be both.

**Comment by patrickkettner** [comment]
> Not sure where you're getting that from but http://caniuse.com/#search=flexbox doesnt currently show that

yes, yes it does. You have to hit "show all", since the usages for ios 5 is so low it is now shown by default.

> it's not gospel and often inaccurate

agree that it _can_ be inaccurate - I have opened up a number of data issues myself. However I really don't "often" is the case. Do you have evidence of that?

> It should be based on what happens in practice

How does iOS 5 not support flexbox legacy in practice?

> you can get very very basic flex to work

Yes, that is what flexbox legacy is (as far as browsers that ever actually shipped support for that syntax)

> if you're lucky

lucky?

> it's generally far to inconsistent to of use

Not sure I follow. Its API is limited, but I am not sure how it is inconsistent. Could you elaborate?

> Regardless there's is still a conflict on ios5 where modernizr reports both no-flexbox and flexboxlegacy at the same time, it can't be both

It certainly can't be both - can you provide a test page where this is happening? I am not able to replicate it with any build.
