### ISSUE TITLE
Firefox Mobile false negative for inputtype: datetime

### ISSUE THREAD

**Issue by jakeparis** [Modernizr/Modernizr#1629]
I'm testing if the browser recognizes the datetime input type like so:
`if (Modernizr.inputtypes['datetime-local'] === false) {
}`
and then displaying a custom datepicker if false. 

In Firefox Android, this test returns false, but it does seem to have the datetime type, causing both the native date/time picker _and_ my custom datepicker to pop up. 

On Firefox desktop, (and all other browsers I've tested) this works as expected.

**Comment by patrickkettner** [comment]
Hey Jake!
Thanks a ton for the report. What OS and what version of ff mobile?

Thanks!

**Comment by jakeparis** [comment]
Android Firefox 40.0
Btw, I also tested like
`Modernizr.inputtypes['datetime-local'] === false && Modernizr.inputtypes['datetime'] === false)`
with the same result. This really sad b/c we just found this bug and are supposed to launch next week.

**Comment by patrickkettner** [comment]
What version of Modernizr are you using?

Is your firefox android traffic really high? The worst case scenario would
be you loading a polyfill, no?

**Comment by jakeparis** [comment]
Well, Firefox Android is not our _largest_ market... :)

/* Modernizr 2.8.3 (Custom Build) | MIT & BSD
 * Build: http://modernizr.com/download/#-flexbox-hsla-input-inputtypes-cssclasses-testprop-testallprops-domprefixes

**Comment by jakeparis** [comment]
In case it helps, I was pointed to this: https://bugzilla.mozilla.org/show_bug.cgi?id=446510#c30 from here: http://stackoverflow.com/a/31974759/362769

**Comment by patrickkettner** [comment]
Ah. Hmm. Well, unfortunately, as mentioned in that ticket, there isn't a
way to detect this in FF mobile until they add it to the IDL. Considering
the low use of this part of the input detect, and FF mobile's market share,
I don't think we will do much about this before its fixed in firefox core.

If this is really important to you specifically, I'd suggest adding a US
sniff for it. Sorry, and good lick in your launch!
