### ISSUE TITLE
Use prefixed function for extends native prototype

### ISSUE THREAD

**Issue by mickaelvalmier** [Modernizr/Modernizr#1634]
Hi,

I want to use function  'Modernizr::prefixed' for extends native element prototype like that : 
```javascript
Element.prototype.requestFullScreen = Modernizr.prefixed('requestFullScreen', Element.prototype);
```

But Chrome say an illegal invocation exeption when i would to call my fonction : 
```javascript
document.documentElement.requestFullScreen();
```

I suppose that's an error caused by binding with element's prototype ?
But is there an another way to implements this feature ?

Regards,

**Comment by patrickkettner** [comment]
How are you invoking it?

**Comment by mickaelvalmier** [comment]
With onclick event : 
<a onclick="javascript:video.requestFullScreen()">FULLSCREEN</a>

**Comment by patrickkettner** [comment]
Please post the code you are using

**Comment by mickaelvalmier** [comment]
Sorry, I have edited my comment.

**Comment by patrickkettner** [comment]
Hey @mickaelvalmier!
Sorry to have been so short before, I was mobile.
Firstly, since this is more of a im-not-sure-how-to-do-this rather then a this-is-broken sort of question, it is more suited for stackoverflow. For future reference,we monitor the Modernizr tag there too.
Secondly - don't override prototypes. You shouldn't change the global object this way. Because other code and libraries may expect another version of it. It's just bad. Try to avoid doing it at all costs.
Thirdly, you shouldn't use inline handlers, look into addEventHandler.

Now, to your original question. More then likely you need to run this frankesnteined version of RFS with call/apply in order to pass the proper "this". E.g.

document.documentElement.requestFullScreen.call(document.documentElement)

**Comment by mickaelvalmier** [comment]
Ok, i understand.

The inline event is just for the example.

Overriding prototype is bad practice but requestFullScreen is functionnality in draft. I would just normalize name of function when i call this in my app.

I have already tried to fix with Function.prototype.call(), but the same error appears.

Thanks for your responses.

**Comment by patrickkettner** [comment]
Post a demo showing the issue

**Comment by mickaelvalmier** [comment]
Ok, here is a small example : 
https://jsfiddle.net/mnLLqtrc/1/

**Comment by mickaelvalmier** [comment]
But, with bracket notation and getting the name of function, this is work :
```javascript
var prefixed = Modernizr.prefixed('requestFullScreen', Element.prototype, false);
Element.prototype.requestFullScreen = Element.prototype[prefixed];
```

**Comment by patrickkettner** [comment]
This really isn't an issue with Modernizr, you shouldn't be overriding the prototype. 

If you need to, fence it off like so

```javascript
if (!("requestFullScreen" in Element.prototype)) {
  Element.prototype.requestFullScreen = Modernizr.prefixed('requestFullScreen', Element.prototype);
}
```
