### ISSUE TITLE
Provide an option or command to generate configuration file from `modernizer` CLI tool

### ISSUE THREAD

**Issue by peterblazejewicz** [Modernizr/Modernizr#1642]
I think the statements on the documentation page for v.3 are somehow exaggerated and contradictory:

> Now you are ready to get your start making your custom build! You can download the configuration file from the build menu (under "Command Line Config").

https://modernizr.com/docs/#using-modernizr-with-javascript

When I'm ready (have installed via NPM) I need to go to website. What if I went just online but have tool installed? Or just starting user of CLI and hit the wall:
[How to use Modernizr v3?](https://github.com/Modernizr/Modernizr/issues/1616)

How about:
```
mondernizr init
```
or similar sounding command option? It could just copy `lib/config-all.js` as default config to the same directory where `modernizr.js` file is created.

The Modernizr is now self-contained tool without dependency on Bower, so it somehow should be able to bootstrap itself for use (`bower init`, `npm init`)

Thanks!

**Comment by patrickkettner** [comment]
Hey @peterblazejewicz!

I agree that the docs could be improved with an example on what a config looks like. Would you be interested in PRing a change to add it [here](https://github.com/Modernizr/modernizr-neue/blob/master/docs/intro.md)?

We actually are trying hard to avoid situations in which people might ship the entire set of detects, because it is massive and wholly unnecessary for most sites. An init command that creates en _empty_ set of detects isn't a bad idea though! A PR would be very welcomed.

If you need any guidance on where to start I would be more than happy to help!

**Comment by patrickkettner** [comment]
forgot to mention

>The Modernizr is now self-contained tool without dependency on Bower, so it somehow should be able to bootstrap itself for use (bower init, npm init)


is this a related thought? there are a number of things that we need from npm...

**Comment by patrickkettner** [comment]
Ping @peterblazejewicz

**Comment by peterblazejewicz** [comment]
@patrickkettner 
I've been playing with update tool during this weekend and have better idea how tool is now envisioned to work (I wondered how will I use it at work).
I think I could do PR in future to create a blanket JSON config file. For this we don't need this issue. So I'll close it now.
The content of blanked JSON could be discussed in PR, as it seems you have not rejected idea. I hope I can contribute to docs in some way.
Thanks!

**Comment by patrickkettner** [comment]
Thanks a lot!
It's totally OK go leave the issue open in case you get too busy to finish
the PR, someone else can find it and carry the torch.

Either way - looking forward to your contribution!
