### ISSUE TITLE
Provide option to download v2

### ISSUE THREAD

**Issue by PJL101** [Modernizr/Modernizr#1643]
Is it possible to provide a legacy v2 download option?

I'm hoping this would (in part) fix https://github.com/Modernizr/grunt-modernizr/issues/118 as a link to v2 could be used instead of modernizr-latest.js

**Comment by patrickkettner** [comment]
Hey @PJL101!

I am not quite sure that I follow. `grunt-modernizr` just needs to be updated to use the npm module as a source rather than downloading the old main file.

We wouldn't want people to download the old version since it won't get bug fixes and already has inaccuracy issues.

**Comment by metaloha** [comment]
Then why wasn't this done at the same time? We have broken builds right now, forcing us to use a downloaded copy of M2 instead of using the Grunt task (which we loved right up until yesterday). Your website even offers up the Grunt config for the task, but the task doesn't work at all anymore.

When will it be fixed? Yes, I use the word "fixed" because it's broken - it doesn't need updating, it needs repair.

**Comment by patrickkettner** [comment]
> Then why wasn't this done at the same time

Because you didn't help with the release. This is stuff we do in our free time, man. For free. For you. To do your job.

**Comment by metaloha** [comment]
Understood, and sorry for the attitude. It's just frustrating, as I'm sure you can imagine. Especially when I have to spend a good chunk of Friday and Saturday manually replacing the file every time the build & deploy process runs on the few sites I'm working on right now.

That said, I personally would have made sure the existing, in-use version kept working until the new & improved version was working as well. It looks like the files still physically exist (at least in the site repo) - would it be much trouble to just allow access to them instead of throwing the 404 error?

GrimaceOfDespair (great name) has a commit on his fork at https://github.com/GrimaceOfDespair/grunt-modernizr/commit/9846457ce8578dede5873fd4cb64e21cf0af9590 that at least purports (I haven't tried it yet) to "fix" the errors by getting the 2 needed files directly from GitHub instead of the website. This isn't a long-term fix, but could the "official" repo do this until v3 is ready?

**Comment by patrickkettner** [comment]
> Understood, and sorry for the attitude. It's just frustrating, as I'm sure you can imagine

no worries mate, and totally. we've all been there.

> This isn't a long-term fix, but could the "official" repo do this until v3 is ready?

Be the PR you want to see in the world.

It will get fixed as soon as someone on the team has time to fix it. It is much easier to make time to review and approve a PR then it is to do it ourselves, however

**Comment by metaloha** [comment]
I'll go learn how to do a PR, it's my first time :)

**Comment by patrickkettner** [comment]
I would LOVE to help you land something. Please feel free to ask anything at all

**Comment by metaloha** [comment]
Thanks :) I think I managed it - https://github.com/Modernizr/grunt-modernizr/pull/119 :)

**Comment by PJL101** [comment]
Hi @patrickkettner 

My inital suggestion was based on an incorrect assumption about how grunt-modernizr was trying to load the script, apologies. Going to self close.
