### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by bramsmulders** [Modernizr/Modernizr#1648]
Hey guys,

is there a reason why there isnt a bower.json anymore. Currently the last version registered with the bower registry is version 2.8.3. And i want to use version 3, but i need to specify the specific commit for that one.

Thnx in advance

**Comment by masi** [comment]
That's because there is no v3.0.0 tag present in the repo.

**Comment by patrickkettner** [comment]
@bramsmulders we never registered a bower version. It was unofficial. Since there is no main file anymore, there is nothing to register.

@masi wat?

You can get bower goodness, though. If you make your custom build on the cli or website, in the header kf the file there is a build URL. Something like

```
https://modernizr.com/download?setclasses-ambientlight
```

If you add a .zip to the end of that, you can now bower install your own custom build!

```
bower install --save https://modernizr.com/download?setclasses-ambientlight.zip
```

Blog post with more info coming soon

**Comment by masi** [comment]
I mentioned the git tag because bower looks for the available tags matching the version set in bower.json.

**Comment by patrickkettner** [comment]
Ah, yes. We have never had a version in the official bower. There isn't
something to install
