### ISSUE TITLE
Modenizr.load() is not available now?

### ISSUE THREAD

**Issue by kravigupta** [Modernizr/Modernizr#1666]
I could not find Modernizr.load() in the new version. Am I missing something? Please help.

**Comment by roblarsen** [comment]
It's been deprecated https://github.com/Modernizr/Modernizr/pull/1241

Apparently if you include yepnope in the page it will work as before for the time being.

**Comment by kravigupta** [comment]
Thanks Rob. I believe after this commit, Modernizr becomes purely feature detection lib?

**Comment by roblarsen** [comment]
I don't know the reasoning, myself.

**Comment by kravigupta** [comment]
hmm.. anyways, thanks for help. Nice talking to you. :) 

--closing the topic.

**Comment by SlexAxton** [comment]
[Creator of Modernizr.load here]

Modernizr.load was always yepnope.js - just aliased. I deprecated yepnope.js (at least the way it used to work), because it goes against best practices, and I didn't want to encourage people, under the guise of performance, to make their sites slower.

Full information on the deprecation here: https://github.com/SlexAxton/yepnope.js#deprecation-notice (also mentioned in the 3.0 release notes)

I'd very much encourage you to adopt conditional builds, and load a single file based on your tests, rather than use old yepnope.js to load a bunch of things separately.

**Comment by kravigupta** [comment]
Thanks Alex, for clarification.

**Comment by alejandroiglesias** [comment]
I would really like to hear if you can recommend other "best practice" alternatives since conditional builds are not for everyone of us.

**Comment by patrickkettner** [comment]
While you should use conditional builds, there is nothing stopping you from using yepnope. What is it you are asking for?
