### ISSUE TITLE
Why there is no select All checkbox

### ISSUE THREAD

**Issue by Randore** [Modernizr/Modernizr#1684]

**Comment by defyjoy** [comment]
+1

**Comment by ryanseddon** [comment]
<img width="962" alt="modernizr__the_feature_detection_library_for_html5_css3" src="https://cloud.githubusercontent.com/assets/143402/12380477/147fff0e-bdc8-11e5-84aa-9edc193952a2.png">

That button will check all tests in the builder. We don't want to promote that on the builder page as it's a very bad idea to have all tests bundled and deployed to a production site since it will slow down you site siginificantly.

**Comment by ryanpcmcquen** [comment]
What keeps you from just doing this?
```js
[...document.querySelectorAll('[type=checkbox]')].forEach(checkbox => { checkbox.checked = true; })
```
It looks like all are checked by default now though.

**Comment by nicewahson** [comment]
complex
