### ISSUE TITLE
Add a pre-built version with most commonly-used detects

### ISSUE THREAD

**Issue by bdkjones** [Modernizr/Modernizr#1691]
When installing Modernizr 3.0 through Bower, there is no longer a pre-built JavaScript file. The argument in favor of this is: "We can give you a smaller JS file if you manually build it yourself and tell us which detects you want to use". 

### The Problem 

That is a valid point. However, this approach has broken a BUNCH of stuff. Take Zurb Foundation. Now, when a user installs Foundation through Bower, Foundation pulls down Modernizr 3.0 and expects there to be a `modernizr.js` file. There is not.

The person that just installed Foundation now has to go build Modernizr. But he or she has *no idea* which detects Foundation uses. So they're going to do the safe thing: build Modernizr with ALL detects enabled. 

Because many, many frameworks (like Foundation) specified their dependency on Modernizr using something like: `modernizr >= 2.7.2`, they all now grab the 3.0 release that has no pre-built JavaScript file. They are all now broken.

### The Correct Fix

When Modernizr is installed through Bower, it should contain a pre-built `modernizr.js` file that has all detects (or at least the most common ones) enabled. This is the safe, sane starting point. It also provides backwards compatibility with the many hundreds of frameworks and tools that declare a dependency on modernizr and expect `modernizr.js` to exist. 

If a user then wants to optimize modernizr further, he or she can build their own custom version. But asking everyone to do that from the start when, in many cases they have NO IDEA which detects are required by the frameworks they're using, is a bad approach. 

Please add the pre-built `modernizr.js` file back to the Bower install.

**Comment by bdkjones** [comment]
An alternative approach would be to ship a pre-built version of `modernizr.js` that contains only the most popular or commonly-used detects.

This avoids the problem where shipping ALL detects slows down page-loads dramatically, but still allows modernizr to be used "out of the box", providing backwards compatibility with the many frameworks that have a modernizr dependency.

**Comment by SlexAxton** [comment]
> it should contain a pre-built modernizr.js file that has ALL detects enabled. This is the safe, sane starting point.

This is in no way a sane starting point. This contributes seconds of blocked rendering to the load time. There are ~250 detects. Some of these have to spin up 3D webgl contexts, others have to base64 inject image types. Most of them are injecting and removing elements to test against.

There's no room in load times for parser and render thrashing. We just need to adjust our processes.

> Because many, many frameworks (like Foundation) specified their dependency on Modernizr using something like: modernizr >= 2.7.2, they all now grab the 3.0 release that has no pre-built JavaScript file. 

The point of major releases is to break backwards compatibility. It is somewhat guaranteed, by definition of major version that putting that into your app will cause something to break.

> It also provides backwards compatibility with the many hundreds of frameworks and tools that declare a dependency on modernizr and expect modernizr.js to exist.

http://bower.io/search/?q=modernizr -- If you look at the owners of these packages, the Modernizr team has never officially released bower or npm versions of modernizr. All of these are various developers that are not affiliated with the project. We wanted to wait until we could ship something that allowed people to not put 250 detects on their page (because everyone ships the defaults). That's why we worked on 3.0 the way that we did.

**Comment by bdkjones** [comment]
I get all of that. But until everyone catches up to your new process, what do you suggest folks installing Foundation do? They've got to build Modernizr to make Foundation work now. And they have no idea which of the 250 detects they should enable. 

No one knows the detects better than you guys. Surely there is some subset of them that can form a good, sane starting set? THAT would be the ideal target for a pre-built version of `modernizr.js`.

And yes, I appreciate that major releases break backwards compatibility. But unfortunately, many frameworks are now pulling down Modernizr 3 when they should have limited themselves to Modernizr 2.x. That's just the reality I'm working with.

**Comment by bdkjones** [comment]
And I don't mean to pick on Zurb Foundation. They're just a prominent example. There are literally hundreds of other projects that rely on Modernizr and are now in the same boat. And while we can talk about how they should have specified `2.x only` in their dependencies, that ship has sailed. 

So does it not make more sense to ask the people that know Modernizr best to distill a set of the most-commonly-used detects and ship those as a pre-built `modernizr.js` file so that the vast majority of these frameworks will continue working?

**Comment by patrickkettner** [comment]
hey @bdkjones!

So, I can't imagine this every happening. This results Its bad for the internet. This results in developers shipping code that have way too much unnecessary code running. It punishes users for developers slight connivence. 

> But until everyone catches up to your new process, what do you suggest folks installing Foundation do?

if they can't update their version of modernizr, change the bower config to point to a 2.X version.

> They've got to build Modernizr to make Foundation work now. And they have no idea which of the 250 detects they should enable.

Neither do we, since we do not use Foundation. Perhaps something like (grunt/gulp)-modernizr can determine that for them?

> Surely there is some subset of them that can form a good, sane starting set?

None is the best starting set. You should only be using what you __need__, not what you __might__ need.

> And yes, I appreciate that major releases break backwards compatibility. But unfortunately, many frameworks are now pulling down Modernizr 3 when they should have limited themselves to Modernizr 2.x. That's just the reality I'm working with.

That is a total bummer, and I am really sorry that that happened. But I am not sure why we would take control of a unoffical package to propagate bad developer behavior just because another framework didn't use dependencies correctly 

![XKCD comic #1172](https://imgs.xkcd.com/comics/workflow.png)

> There are literally hundreds of other projects that rely on Modernizr and are now in the same boat.

What boat is that? Nothing is stopping anyone from using Modernizr 2.X. Update the bower config.

> And while we can talk about how they should have specified 2.x only in their dependencies, that ship has sailed

If the "ship has sailed", what can be done? 

> So does it not make more sense to ask the people that know Modernizr best to distill a set of the most-commonly-used detects and ship those as a pre-built modernizr.js file so that the vast majority of these frameworks will continue working

As I laid out previously, I do not think it does make sense.




Now. Do not despair, we are 100% pro bower/npm. We just think that they should be used when (with modernizr) for custom builds. That is why we created the bower build service. Make a custom build, grab the url from header in the file, throw a `.tar` at the end of it, and you will have a bower installable file

e.g. `bower install --save  https://modernizr.com/download?canvastext-setclasses.tar`

Foundation, or anyone else for that matter, can create a build of Modernizr that uses their exact needs, add that url to the bower config, and you will have a working set.

Since we will not be implementing a "main" modernizr file, I am going to close this issue. I am really sorry that you are having to deal with the fallout from this. It really sucks. But there is a multitude of fixes available to get y'all out of it. Shipping a bloated default Modernizr is not one of them.

**Comment by bdkjones** [comment]
Thanks for the reply. 

Which detects would I need to build in 3.0 to get back to what the pre-built version of `modernizr.js` had in the last release of 2.x? I suppose that's what I'm going to have to do for now, until all the authors catch up to what you guys have done.

**Comment by patrickkettner** [comment]
Well, again, I would not suggest doing that. I would suggest running grunt-modernizr against your codebase and finding the ones you are _actually_ using, rather than just blindly adding detects and burning through your user's batteries. 

The old build can be found [here](https://github.com/Modernizr/Modernizr/blob/backport-fixes/modernizr.js).

I am curious, however. If you can update your site to change the Modernizr config, why can't you just use the latest Modernizr 2.X release? Its never going to be updated. just hardcode it until you can manage a proper fix

**Comment by bdkjones** [comment]
I don't have a site. I write CodeKit, which does 1-click Foundation installs. And right now, the installed version of Foundation doesn't work because Modernizr is no longer pre-built in 3.0. 

I'm just trying to handle the transition. Eventually, Zurb needs to update the Foundation install process to build the exact version of Modernizr they need. Or, more likely, they'll just update the dependency to stay on 2.x. 

But that's not under my control and I don't want to ship a version of my app that hardcodes Modernizr 2.x if Zurb is going to update their process to support Modernizr 3. Because then I'll have thousands and thousands of users installing Foundation with my "just use 2.x" hack long after Zurb has updated to officially support Modernizr 3.

**Comment by patrickkettner** [comment]
> I don't have a site. I write CodeKit, which does 1-click Foundation installs. And right now, the installed version of Foundation doesn't work because Modernizr is no longer pre-built in 3.0.

ok, sorry my my confusion. But I think the root of the question still stands. How would you use the modular builder to recreate v2 in v3, butnot be able to change the bower config to pin the version?

**Comment by bdkjones** [comment]
I *can* do both. But the problem is that once I ship a version of my app that does either, that version of the app will stay in use for a LONG time (because people don't update immediately when I release new versions). 

Which means that if I hack bower.json file to just use Modernizr 2.x, then 10 months from now---LONG after Zurb has officially updated to support Modernizr 3---that version of my app will still have a significant number of people using it and installing the old, hacked approach.

I'm very careful what I ship because it sticks around for a substantial period of time. I try very hard to avoid hacks when I can get framework/tool authors to address problems directly and officially.

**Comment by patrickkettner** [comment]
(sorry for the dumb questions, I haven't used codekit)

Can they update their one click install of Zurb without update codekit?

**Comment by bdkjones** [comment]
The Foundation install process goes like this:

1. Clone a Git repo provided by Zurb.
2. Run Bower to install components
3. Compile sources (sass, etc). 

The "fix" from my end would be to perform step 1, then open the `bower.json` file and change the dependency to `modernizr 2.x`. But when Zurb updates their Git repo with official support for Modernizr 3, the "fix" would still be in place and I'd have to issue another app update to remove the "fix". 

What needs to happen, eventually, is Zurb needs to update their Git repos with official support for Modernizr 3, which will involve specifying a custom build configuration and then running that build after running Bower to pull down Modernizr.

**Comment by bdkjones** [comment]
Also: I'm not opposed to the grunt-modernizr scanning approach. But didn't you guys change the name of some detects between 2.x and 3.x? (I saw a note about removing hyphens). 

Are the old, hyphenated names forwards-compatible with Modernizr 3?

**Comment by patrickkettner** [comment]
> The "fix" from my end would be to perform step 1, then open the bower.json file and change the dependency to modernizr 2.x. But when Zurb updates their Git repo with official support for Modernizr 3, the "fix" would still be in place and I'd have to issue another app update to remove the "fix".


Couldn't it be something like this

```
readFile('bower.json', function(content) {
  var bowerJSON = JSON.parse(content);
  if (bowerJSON.version === '>= 2.7.2') {
    // modify bower
  }

  bower.install()
})
```

That being said, foundation [updated this about 8 days ago](https://github.com/zurb/foundation/commit/925abff29681c85c6e55c4497274f97c780b0ced). Does that matter at all?


> Also: I'm not opposed to the grunt-modernizr scanning approach. But didn't you guys change the name of some detects between 2.x and 3.x? (I saw a note about removing hyphens).

grunt-modernizr has v3 support

> Are the old, hyphenated names forwards-compatible with Modernizr 3?

yeah, they have an `aliases` prop

**Comment by bdkjones** [comment]
It actually looks like Zurb has already officially pinned Foundation to Modernizr 2.7.2: https://github.com/zurb/foundation/commit/925abff29681c85c6e55c4497274f97c780b0ced

This change just hasn't made it out to the Git repos that form the installation templates, though. I'll follow up with them.
