### ISSUE TITLE
calling modernizr.build in Node JS more than once at the same time

### ISSUE THREAD

**Issue by hedgehog90** [Modernizr/Modernizr#1832]
How can I run 2 builds at the same time?
If I call
```
require("modernizr").build({}, function (result) {
    console.log(1);
});
require("modernizr").build({minify: true}, function (result) {
    console.log(2);
});
```
Then only the second callback runs, but it runs twice!
So the output is:
```
2
2
```

This seems to me a very odd design choice. I'd like to fix it so I can call more than 1 build at the same time in nodejs.
How do I do this?

**Comment by patrickkettner** [comment]
So, this was a stupid mistake on our (well, my) part

what was happening was clobbering of a global config object. So that when the async callback was called on the build completion, the second build's config had overwritten it. This is patched in #1832, waiting on travis to give the thumbs up then I will do another release

**Comment by hedgehog90** [comment]
Oh right! I just figured that's how it was supposed to work.
I've just spent hours rewriting my website compiler to suit the modernizr.build function... Wish you hadn't told me that now.

**Comment by patrickkettner** [comment]
not sure I understand what you are saying.
