### ISSUE TITLE
SVG : <use> balise can be detected ?

### ISSUE THREAD

**Issue by pgrmCreate** [Modernizr/Modernizr#1899]
Good morning,

Modernirz can detect the functionnality of < use > balise in SVG ? What components use ?

**Comment by patrickkettner** [comment]
Can you explain what you mean? I am not quite clear on what it is you are asking for

**Comment by eweap** [comment]
I think @pgrmCreate want to know if there is a way, with Modernizr, to detect the support of the `<use>`  element who reference external resource.

This element wasn't supported on IE until [EDGE](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6263916-svg-external-content?tracking_code=85a4cffafffac0497bb5074ed03d43f5) so it can be useful to have a way to detect the support of the browser for loading a polyfill ([like this one](https://github.com/Keyamoon/svgxuse))

[W3C Spec](https://www.w3.org/TR/SVG/struct.html#UseElement)

Thanks

**Comment by pgrmCreate** [comment]
Excuse me @patrickkettner, i was not clear. Effectively @eweap, I speacking  about this problem subject.

**Comment by patrickkettner** [comment]
unfortunately, because of the same origin policy, this isn't possible for Modernizr to test. Since we can't rely on external resources, we would normally fall back to data uris (like a base64 encoded svg). But you can't load a data uri from an inline svg. I tried putting a data uri as a external ref inside of another data uri and load that as an image, but it doesn't work. I believe this is just undetectable for Modernizr
