### ISSUE TITLE
Detect whether javascript is executed while scrolling?

### ISSUE THREAD

**Issue by yn5** [Modernizr/Modernizr#1971]
Especially in older mobile browsers sometimes javascript is paused during scroll events. Although it doesn't seem to be part of Modernizr I thought this might be a good place to ask: Is there any known way to detect whetger a browser will execute javascript while scrolling?

**Comment by patrickkettner** [comment]
Since this isn't really a feature of browsers, modenrizr wouldn't be a great place to have this sort of a detect (at least in core - perhaps as a modernizr plugin for your own code?). 

I have no idea, but perhaps running a requestAnimationFrame/setInterval loop and change the scoll offset, then check how many times the lop ran compared to the same amount of with out changing it? Doubt it would work, but thats the only thing I cna think of without user input :/

good luck!
