### ISSUE TITLE
Modernizr.mq conditional not working on iOS

### ISSUE THREAD

**Issue by davetgreen** [Modernizr/Modernizr#1996]
I'm doing a very simple addition of a class to a div if it's under a certain viewport width e.g.

````
        if (Modernizr.mq('(max-width: 1024px)') {

            el.addClass(className);

        } else {

            el.removeClass(className);
            
        }
````

**NB:** I've decided with max-device-width as well.

It seems that this just doesn't fire for an iPhone, but it does for other mobile devices (granted, predominantly Android ones) as well as when I view in a re-sized desktop browser.

Is this a known issue or have I simply overlooked something obvious?

**Comment by patrickkettner** [comment]
Not quite sure based on what you said, but to be clear this code runs a single time.

You are not listening to any events in the code, so it won't be reevaluated when anything changes (since it doesn't have a way to be notified of changes). Nothing will ever be fired. You are doing the equivalent of `if (screen.width >= 1024)`

Does that clear up anything?

**Comment by davetgreen** [comment]
Hi @patrickkettner, sorry I should have elaborated on the code set-up.

I'm firing the function that encloses my code example when the document is ready, but also on window re-size with throttling. Here's a more complete picture...

````
jQuery(function($) {

    ...

    var resizeTimer;

    function mobileMenuClass() {
        var el = $('.site-identity');
        var className = 'mobile';

        if (Modernizr.mq('(max-width: 1024px)')) {

            el.addClass(className);

        } else {

            el.removeClass(className);

        }
    }

    mobileMenuClass();

    $(window).resize(function() {

        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(mobileMenuClass, 100);

    });

}(jQuery));
````

As I say, it's working as expected on anything but on iPhone at the moment. Fortunately Modernizr adding the `data-platform="iPhone"` attribute means I've been able to implement the same styling via CSS as I would be able to with the class added.

**Comment by davetgreen** [comment]
I think I'm just going to put this down to a project specific issue, as on reflection I'd be surprised if Modernizr was actually at fault.

**Comment by patrickkettner** [comment]
if you happen to open up an issue anywhere else (stackoverflow or something), feel free to ping on here. happy to help reduce

**Comment by odysseuscm** [comment]
I think I found the problem:
Apple's Safari an iOS has a bug(?) where it reports the body size of the browser independently from the screen orientation. Meaning x size of body is always as if in landscape mode (1024px on iPad Air), even if you hold the device in portrait mode. (Firefox on Android used to do that too, if you didn't give it some time to recalculate.) That's why I use window.innerWidth instead on iOS (and Android) to get the viewport size which correctly reports 768px in portrait mode.
But CSS Media Queries work as expected on iOS, so (max-width: 990px) only applies to the iPad Air used in portrait mode.
I don't know what kind of magic is used for Modernizr.mq() but Modernizr.mq('(max-width: 990px)') reports "false" on an iPad held in portrait mode. Since I believe the whole point of Modernizr.mq() is to get the same reponse as with CSS Media Queries, this is a relevant bug. Please verify this.
I'm not sure my method of using window.innerWidth is entirely foolproof either, since the iPad Pro is now capable of displaying two apps next to each other, so there might be problems with that as well (lacking an iPad Pro I cannot test). Maybe a combination of asking for device orientation and body size is neccessary to always get the correct result on iOS.

**Comment by davetgreen** [comment]
@odysseuscm Top work sir! Everything you've described is exactly how I experienced it 👍

I'm glad I posted this issue now!
