### ISSUE TITLE
Modernizr and loading fonts over HTTPS

### ISSUE THREAD

**Issue by Eligioo** [Modernizr/Modernizr#2039]
I recently swithed my website over to a SSL connection but somehow, Modernizer keeps loading fonts over HTTP wich results into refused connections.

I found this issue on stackoverflow: http://stackoverflow.com/questions/25646739/why-is-modernizr-loading-google-fonts 
I dont get why fonts dont get loaded automatically based on the connection type?

For example I'm talking about fonts like these who get loaded: http://fonts.gstatic.com/s/opensans/v13/xjAJXh38I15wypJXxuGMBo4P5ICox8Kq3LLUNMylGO4.woff2

**Comment by patrickkettner** [comment]
Modernizr does not load any external file.

The error in stack overflow is showing how an ssl error occurs because it used to inject the string `http://` into the page (note that its just http - no external domain or url or anything else) to see if it was parsed correctly. This was used to detect if the browser supported font-face fonts. This particular issue hasn't existed in Modernizr for years however, since we switched out detection methods to not do this at all.

Nothing Modernizr does would be loading the file you reference. It is possible that somewhere in your code someone is calling `Modernizr.load` to dynamically inject the file, but it would not be from Modernizr's code. 

If you share the url of the site, I would be happy to help debug it futher, but without it, there is nothing for us to do.

**Comment by patrickkettner** [comment]
closing because of no response, please let me know if you have any further info @Eligioo :]

**Comment by kapilkd13** [comment]
Hi I am facing a similar issue. I have recently started a blog on github that uses modernizr.js. Problem is some of the icons are not rendered and I get a "this page is trying to load unsafe scripts". On loading this "unsafe scripts" I get the fonts. When I looked into the console I got
 ```
modernizr.js:8 Mixed Content: The page at 'https://kapilkd13.github.io/blog/gsoc/GSOC-Week-0' was loaded over HTTPS, but requested an insecure font 'http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/fonts/fontawesome-webfont.woff?v=4.1.0'. This request has been blocked; the content must be served over HTTPS.
```
Here is my blog https://github.com/kapilkd13/blog
You can see the problem here https://kapilkd13.github.io/blog/gsoc/GSOC-Week-0 as in footer fb/google and other icons are not rendered over https.

**Comment by patrickkettner** [comment]
@kapilkd13 as you can see in the error message, this has nothing to do with modernizr. You are attempting to load the font over http, when it needs to be loaded over https.

```html
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700|Open+Sans:400,600,300,800,700' rel='stylesheet' type='text/css'>
```

needs to be changed to 

```html
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700|Open+Sans:400,600,300,800,700' rel='stylesheet' type='text/css'>

```

**Comment by kapilkd13** [comment]
Hi @patrickkettner  I solved by changing `http://fonts.googleapis....` to `//fonts.googleapis...` so that it can load over both `http` and `https`. Thanks 😄

**Comment by patrickkettner** [comment]
thats generally considered an antipattern these days. If possible, _all_ traffic should be sent via https

glad its sorted!

**Comment by ADTC** [comment]
Hi, I'm getting this error in Modernizr 2.8.3 but I can't seem to find the problem. (I thought I'd just replace `http://` with `//` (relative protocol).) It appears to be the [lines 457-459 in the source code for v2.8.3](https://github.com/Modernizr/Modernizr/blob/v2.8.3/modernizr.js#L457). I went through everything in my project and I couldn't find any reference to the `woff` file it's trying to load. Any hints on how to rectify this?

> Blocked loading mixed active content “http://api.jquery.com/jquery-wp-content/themes/jquery/css/fonts/fontawesome-webfont.woff?v=3.0.2”
[Learn More](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content)
modernizr-2.8.3.min.js:4:3956

```
          injectElementWithStyles(['@media (',prefixes.join('touch-enabled),('),mod,')','{#modernizr{top:9px;position:absolute}}'].join(''), function( node ) {
            bool = node.offsetTop === 9;
          });
```

![image](https://user-images.githubusercontent.com/6047296/33521906-7d226ca0-d805-11e7-8aee-3f0a0ff47fec.png)

**Comment by Skadi2k3** [comment]
I can't replicate your error. Have you updated https://beta.molinosph.com/product/42 ?

**Comment by ADTC** [comment]
I have some updates **but I didn't change anything as far as Modernizr is concerned.**

_Weird, I don't get the error anymore in Firefox Inspect. Must have been an intermittent issue. Thank you guys for your attempts to replicate._

**Comment by ADTC** [comment]
@Skadi2k3 appreciate if you can remove the URL from your comment. Thanks. **You can say "Have you updated your site?"**
