### ISSUE TITLE
videoautoplay and Safari iOS 10

### ISSUE THREAD

**Issue by grmlin** [Modernizr/Modernizr#2071]
With iOS 10 Safari added autoplay for videos. It does only work with muted videos or videos without sound though.

right now, the `videoautoplay` test is positive, as I think the test video used is without sound?

The problem I see is, that a simple true/false might not be enough here? Maybe another test checking  if the video autoplays with sound would help?

**Comment by patrickkettner** [comment]
hey @grmlin!

In cases like this, where it works, just not always, we tend to prefer the positive rather than the negative. Especially since autoplaying videos with sound, (even moreso those on mobile) are generally terrible (not that they are without use, just most uses are awful). 

I am going to say a `wontfix` on this :/, but if y'all want to try it it would be a straightforward detect to create if you control an external resource (Modenrizr can't). Check out the test we are using, and replace the base64ed mp4 with the link to your file and bobsyourunvcle

good luck!

**Comment by grmlin** [comment]
Hey,
thanks for the quick response. 

That whole "we can now autoplay on mobile devices" thing is a mess. I don't like that, I don't want my phone to autoplay videos and waste my limited data volume. And I can't even turn it off in the settings afaik. :(

Sadly I have to deal with that as a developer now, and I'll have to know if a video will start or not for some clients. I'll add my own test based on the existing test with sound then, I'll post a gist in here if I'm done, but it will take some time as I don't need it right now.
