### ISSUE TITLE
Sanitization bypass using HTML Entities (SEVERITY: HIGH)

### ISSUE THREAD

**Issue by victoriafrench** [Modernizr/Modernizr#2158]
# Content & Code Injection (XSS)
#### SEVERITY: HIGH
Sanitization bypass using HTML Entities
Discovered in a nested dependency: modernizr@3.3.1 -> marked@0.3.5

#### Overview

`marked` is a markdown parser and compiler used for rendering markdown content to html. It is vulnerable to content injection attack allowing the attacker to bypass its output sanitization (`sanitize: true`) protection. Using the [HTML Coded Character Set](https://www.w3.org/MarkUp/html-spec/html-spec_13.html#SEC13), attackers can inject `javascript:` code snippets into the output. For example, the following input `javascript&#x58document;alert&#40;1&#41;` will result in `alert(1)` being executed when the user clicks on the link.

#### Remediation

Upgrade `marked` to version **0.3.6** or higher. Alternatively, you can use `remarkable` or other markdown libraries.

PUBLISHED 20 Apr, 2016
[Reference](https://snyk.io/vuln/npm:marked:20150520)

**Comment by rejas** [comment]
Was fixed a while ago with https://github.com/Modernizr/Modernizr/pull/2027

**Comment by blackfly06** [comment]
xss:ex/*XSS*//*/*/pression(alert("XSS"))'>

**Comment by blackfly06** [comment]
';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//";alert(String.fromCharCode(88,83,83))//";alert(String.fromCharCode(88,83,83))//--></SCRIPT>">'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>

**Comment by rejas** [comment]
anything you want to tell us @blackfly06  ?

**Comment by Trott** [comment]
The vulnerable code here is used to generate metadata and documentation. It does not appear in the modernizr library used by the browser. So this is an issue for the `modernizr` module on `npm` because it is not the library used in the browser but rather the tool used to build the library used in the browser.

In other words, if some vulnerability scanning tool is flagging this in a web page, that is a bug in the scanning tool. Since this has now happened twice to me with two different sites, I'm guessing I'm not alone in experiencing this and posting this here in case it might help someone else. (Confirmation from someone on the Modernizr team would probably enhance the credibility of this comment.)
