### ISSUE TITLE
Indexeddb throws exception in Firefox 12

### ISSUE THREAD

**Issue by NotMrSteve** [Modernizr/Modernizr#2192]
Modernizr does not run on Firefox 12 when indexeddb detection is included.

In Firefox 12
`var req = indexeddb.open(testDBName)`
throws a `NS_ERROR_DOM_INDEXEDDB_UNKNOWN_ERR` exception.

Including modernizr.js on any page that is loaded in FF12 will cause this (see Console logs). Tested on MacOS and Windows 7 with non-minified and minified JS. Occasionally it will even cause Firefox to crash (occurred running the minified JS, hard to reproduce, but also occurs on Windows & MacOS).

Can be easily prevented by enclosing the call to `indexeddb.open()` in a `try {} catch {}`.

**Comment by patrickkettner** [comment]
hey @NotMrSteve !
thanks for opening an issue.
We generally don't address bugs for old versions of evergreen browsers, since the market is almost always super duper small. Firefox 12 is a half decade old at this point, so we wouldn't be inclicned to fix it unless it is also an issue in later versions, or 12 was an ESR or really popular in some markets.

Is any of that the case?

**Comment by NotMrSteve** [comment]
None of that is the case, but it's literally a 3 line change to add the `try {} catch {}` around the offending code! (I've done it, but I can't push the code here) :)

And it doesn't occur in indexeddbblob because there exists a `try {} catch {}` around the offending call.

**Comment by patrickkettner** [comment]
is there still an issue in modern versions of firefox?

**Comment by NotMrSteve** [comment]
No, new versions are fine.

**Comment by patrickkettner** [comment]
While I understand the frustration of not fixing such a simple bug, it is a death-by-a-thousand-cuts thing from the maintainers point of view. We don't want to add code to support an old version of an automatically updated browse because it just means that a vast majority of folks who have to download the code will never ever use it. If we added simple fixes for all browser versions, we would more than double our size in no time.

I really do appreciate you taking the time to open the issue, but in light of how little used the browser is, we will not be patching it. I it is important to you or any other developer, than it is simple enough to manually patch your build of modernizr.
