### ISSUE TITLE
datauri test creates deprecation warning on chrome 59

### ISSUE THREAD

**Issue by ViceIce** [Modernizr/Modernizr#2216]
Resource requests whose URLs contain raw newline characters are deprecated, and may be blocked in M60, around August 2017. Please remove newlines from places like element attribute values in order to continue loading those resources. See https://www.chromestatus.com/features/5735596811091968 for more details.

The warning is thrown at [feature-detects/url/data-uri.js#L75](/Modernizr/Modernizr/blob/master/feature-detects/url/data-uri.js#L75)

The test was introduced by #321

**Comment by bs-thomas** [comment]
@ViceIce So aside from ensuring that newlines do not exist in element attributes, do we have to do anything else?  Is it recommended to exclude this feature from the modernizr build for projects?

**Comment by ViceIce** [comment]
@bs-thomas I don't know. I only found the message on my debugger and checked where it comes from.

**Comment by patrickkettner** [comment]
Hey @ViceIce thanks for the heads up! This actually doesn't affect anything other than causing some mild spam in your console.

@bs-thomas you almost certainly can remove this tet from your build unless you need to support IE7

Since it doesn't affect our test, and is needed for it, im closing as a wontfix - but thanks again for reporting!
