### ISSUE TITLE
Bug: "Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules"

### ISSUE THREAD

**Issue by liuhelen10** [Modernizr/Modernizr#2296]
## Problem
We are using the build [generated with these options](https://modernizr.com/download/?applicationcache-audio-backgroundsize-borderimage-borderradius-boxshadow-canvas-canvastext-cookies-cssanimations-csscolumns-cssgradients-cssreflections-csstransforms-csstransforms3d-csstransitions-filereader-flexbox-flexboxlegacy-fontface-generatedcontent-geolocation-hashchange-history-hsla-indexeddb-inlinesvg-input-inputtypes-localstorage-multiplebgs-opacity-postmessage-rgba-sessionstorage-smil-svg-svgclippaths-textshadow-video-webgl-websockets-websqldatabase-webworkers-domprefixes-hasevent-mq-prefixes-setclasses-shiv-testallprops-testprop-teststyles) in our codebase, and noticed that this error has been cropping up recently:

```
Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
```

I believe the issue is coming from the following chunk of generated code:

```
o=a?a.cssRules&&a.cssRules[0]?a.cssRules[0].cssText:a.cssText||"":""
```

This seems to be occurring because Chromium 64+ forbids the browser from accessing `cssRules` for cross-domain sheets (see https://github.com/odoo/odoo/issues/22517).

## Possible solution
Potential fix (linked from the above issue): https://github.com/odoo/odoo/commit/a6e66131ce5b676ccc888ec5b1011d0946dc3907

**Comment by ham2qur** [comment]
https://github.com/odoo/odoo/pull/22603/commits/33349ed34e45b7e06281c5947645c38b3b29e8b6

**Comment by jescalan** [comment]
I have also been consistently seeing this error, would be great to get a fix going! Would a PR directly to this repo help?

**Comment by Reechee88** [comment]
i am still faceing the problem

**Comment by patrickkettner** [comment]
There really isn't a way to fix this in chrome, outside of you shipping your code on the same domain as the css. That being said, you should almost certainly not be using `@​font-face` detection. 

![image](https://user-images.githubusercontent.com/465414/39417113-0192ea80-4c07-11e8-8b2c-49529df3dab3.png)

The best course of action if you are finding this bug is the not use that detect. If you _do_ need to actually detect `@f​ont-face`, (please comment because I would love to know the reasoning) you can serve the assets on the same domain.

**Comment by xmars4** [comment]
If you're using google chrome, disable it's extension and check again
