### ISSUE TITLE
Update cdnjs-libs?

### ISSUE THREAD

**Issue by michaelsteffen1982** [Modernizr/Modernizr#2351]
Not really an issue, is there a reason libs on cdnjs are still on 2.8.3?
Can you please update them if the 3.*-releases are working fine? Many thanks.

**Comment by rejas** [comment]
question is who got the rights to do that, @patrickkettner ?

**Comment by patrickkettner** [comment]
we never maintained the cdnjs version, nor do we recommend anyone use it. It has far too much code in it than any modern website needs. It is from a time where there was a monolithic modernizr file. Since 3.0 moved to a bunch of modules that can create the exact build needed for your site, you can have the same practical use at a much smaller cost.

**Comment by rejas** [comment]
Can we somehow make it "deprecated" there, maybe add some comments about it non-usefulness or something ?

**Comment by patrickkettner** [comment]
We don't own it, or ever had anything to do with it. Not sure how to go about doing it

**Comment by rejas** [comment]
I found some discussions on cdnjs githubs page https://github.com/cdnjs/cdnjs/issues/6100 Do you want to post here "our" stance :-)

**Comment by patrickkettner** [comment]
Go for it

**Comment by rejas** [comment]
Done :-) Lets see what the cdnjs people will say
