### ISSUE TITLE
Chrome WebView passing tests that should fail

### ISSUE THREAD

**Issue by snout-o** [Modernizr/Modernizr#2366]
I'm currently trying to detect when a browser supports the uploading of files, primarily because we have users scanning our QR codes that take them to a website where the uploading of files is essential.

When using an Android QR scanner that opens a scanned URL internally within a WebView - rather than opening in an external web browser - we find that the File Upload functionality does not work. When tapping the button that should open the file/photo/camera input selector, instead nothing happens.

I've tried using the "fileinput" test within the WebView of a QR scanning app but to my surprise the test returned True, rather than False.

According [to this page](https://developer.chrome.com/multidevice/webview/overview#does_the_new_webview_have_feature_parity_with_chrome_for_android_) the file input feature should not be supported in the Chrome WebView so my expectation was that Modernizr would return false to the "fileinput" test. Have I misunderstood the purpose of this test?

For what it's worth I also tried the "fullscreen" and "filereader" tests and they also returned True. I'm using [this QR app](https://play.google.com/store/apps/details?id=app.qrcode) to test.

The WebView user agent is:

Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJS25.93-14-18; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 Mobile Safari/537.36

(Perhaps I could check for the existence of "wv" but I'd like to not have to do agent sniffing if possible).

**Comment by patrickkettner** [comment]
> Have I misunderstood the purpose of this test?

@snout-o the detect checks to see if the file input type is supported, not if it can be successfully uploaded. Depending on how they are blocking the support in the web view, this may or may not work. That would require a server side element, which we can't rely on in the library. 

That being said, the [input detect](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/forms/fileinput.js) has a large chunk of UA sniffing in it because of weird edge cases like this. Assuming you can confirm that `var i = document.createElement('input'); i.type='file'; i.type === 'file'` is `true`, then we would accept a PR that modifies the UA sniff to grab this as well

**Comment by snout-o** [comment]
Thanks for the quick reply @patrickhlauke I have just performed a quick and dirty test of your code and can confirm i.type === 'file' is true within the WebView.

I'm not sure I'm capable of producing an adequate PR but I will certainly give it a go. Cheers!

**Comment by patrickkettner** [comment]
looks like the [regex](https://github.com/Modernizr/Modernizr/blob/3072bb9dc720345bd6d972aba60314e6fe34427a/feature-detects/forms/fileinput.js#L17) could be based on [this from ua-parser](https://github.com/faisalman/ua-parser-js/commit/a56c990ec32f105219570d398f3398f9373b5a75)

**Comment by snout-o** [comment]
Yep that worked well for my needs. I've made a pull request #2367 for this. I added an extra conditional regex since the original does not define the /i flag and I didn't want to risk affecting that check. I hope I did this right!
