### ISSUE TITLE
Form validation lacks some helpfulness

### ISSUE THREAD

**Issue by smares** [Modernizr/Modernizr#2564]
The check for form validation lacks some helpfulness as it doesn't tell if the browser supports `checkValidity` per form or per form input element, nor does it say anything about the support for `reportValidity`. IE11 for example does support `checkValidity` for forms, but not `reportValidity` which is something one might want to do as latter invokes interactive form validation using the browser's own validation error messages.

**Comment by roblarsen** [comment]
I think that's by design. I bet adding checkValidity and reportValidity tests would be pretty easy. 

>/* DOC
This implementation only tests support for interactive form validation.
To check validation for a specific type or a specific other constraint,
the test can be combined:
- `Modernizr.inputtypes.number && Modernizr.formvalidation` (browser supports rangeOverflow, typeMismatch etc. for type=number)
- `Modernizr.input.required && Modernizr.formvalidation` (browser supports valueMissing)
*/

**Comment by smares** [comment]
I understand, so actually `formvalidation` refers to interactive validation and `formvalidationapi` to non-interactive. Sorry, my bad then.
