### ISSUE TITLE
dragndrop stoped working?

### ISSUE THREAD

**Issue by iwasherefirst2** [Modernizr/Modernizr#2574]
I am using this build for a couple of years now: http://modernizr.com/download/#-fontface-backgroundsize-borderimage-borderradius-boxshadow-flexbox-hsla-multiplebgs-opacity-rgba-textshadow-cssanimations-csscolumns-generatedcontent-cssgradients-cssreflections-csstransforms-csstransforms3d-csstransitions-applicationcache-canvas-canvastext-draganddrop-hashchange-history-audio-video-indexeddb-input-inputtypes-localstorage-postmessage-sessionstorage-websockets-websqldatabase-webworkers-geolocation-inlinesvg-smil-svg-svgclippaths-touch-webgl-shiv-mq-cssclasses-addtest-prefixed-teststyles-testprop-testallprops-hasevent-prefixes-domprefixes-load

And I always checkd if drag and drop is supported by the browser with this check:

```
if(Modernizr.draganddrop && 'FormData' in window && 'FileReader' in window){
..
}

```

However, it seems that `Modernizr.draganddrop` suddenly returns `undefined` in Firefox and Chrome. I could not find `draganddrop` in the browsers features:

![image](https://user-images.githubusercontent.com/1765602/85280024-a9c3fd80-b487-11ea-8e54-871925bc6a03.png)

Any advice?

**Comment by MarkelFe** [comment]
Hi Adam 👋, the drag and drop test was removed in version 3.0.0 back in September 2015. It was due to mobile browsers supporting the API but not making them available to end users, this behavior resulted in false positives. It doesn't appear on the website as the web is providing now the 3.6.0 version (a little bit outdated, but newer than 3.0.0).

You may [check the changelog](https://github.com/Modernizr/Modernizr/blob/master/CHANGELOG.md#v300), it may also be interesting to check #1585, #1127 and #637 (there may be other interesting issues too). In case it is useful for you [here is the file before removal](https://github.com/Modernizr/Modernizr/blob/3cad259ad2ff1bf13dbc3f5ba2f08cc692b1d79f/feature-detects/draganddrop.js), you may be able to re-implement it in your private server, but beware the false positives. Finally, if you find another way to detect the draganddrop API without the false positives, a PR or issue describing the procedure would be super welcomed :)

Anything else leave a comment 😊

**Comment by iwasherefirst2** [comment]
@MarkelFe thank you for that detailed response. I understand that it was dropped in `3.0.0` but it strange that it stopped working, because I was using Modernizr 2.8.3 and it worked since 2015 till recently. 

Anyway, since it has false positives, probably good to remove it in my code aswell.

If I happen to find out how to detect dragndrop without false positives, I will come back.

Cheers,
