### ISSUE TITLE
Footer looks pretty basic.

### ISSUE THREAD

**Issue by arya312** [Modernizr/Modernizr#2712]
Framer-motion or other beautifying affects like color change on clicking/hovering can be added. Moreover, to differentiate the footer from the main page of the website, its color could be changed. iframe could be used to make the words pop-out and look more interactive.

**Comment by rejas** [comment]
Is this about the npm website too?

**Comment by YashasviChaurasia** [comment]
@josh @mislav @arya312 I would like to work on this issue.
Could you please assign it to me if it is available?
Thank you

**Comment by rejas** [comment]
@YashasviChaurasia what footer do you think will be done in this issue?

Because this repo is about the Modernizr library, not the website modernizr.com. But I think the original poster ment the footer on the npm site.

I will close this issue, if anybody wants to work on the modenrizr.com website, he should open an issue on the correct repository: https://github.com/Modernizr/modernizr-neue
