### ISSUE TITLE
fullscreen FD out of date

### ISSUE THREAD

**Issue by miketaylr** [Modernizr/Modernizr#739]
https://github.com/Modernizr/Modernizr/blob/master/feature-detects/fullscreen-api.js

There is no `cancelFullScreen` on document anymore. There is `document.exitFullscreen` however.

**Comment by annevk** [comment]
https://modernizr.com/news/modernizr-3-new-release-site mentions this as properties existing on `window` which seems bogus... Also, https://fullscreen.spec.whatwg.org/ is the latest standard. And `window/document.cancelFullscreen` doesn't exist.

**Comment by patrickkettner** [comment]
Hey @annevk! Thanks a lot for the heads up

how is this?

* `fullscreen` detect has been updated to use `document.exitFullScreen` rather than the prefixed versions of `document.cancelFullScreen` as per [the latest spec](https://fullscreen.spec.whatwg.org/) ([#739](https://github.com/Modernizr/Modernizr/issues/739))

**Comment by annevk** [comment]
Looks better, thanks.
