### ISSUE TITLE
Detecting a mouse user

### ISSUE THREAD

**Issue by paulirish** [Modernizr/Modernizr#869]
Let's use this ticket just to explore the ideaspace. Basically... is there a way to detect a mouse user?

just random notes on detection in this area:
### touch evts & input exclusivity

Can't make assumptions about input anymore...
- Just because touch events are present doesn't mean the user is primarily using a touchscreen.  Or that there is no mouse.
- Just because there are touch events supported doesn't mean :hover styles will never be triggered.  
- Just because there is a mouse doesn't mean people can't also touch the screen.
- ~33% of iPad users with VoiceOver enabled use an attached keyboard. (@stevefaulkner said this, iirc)

http://www.html5rocks.com/en/mobile/touchandmouse/ by @cwilso is a must read for this space.

(and when this ticket says "mouse user" it means _currently using a mouse but may mid-session switch to touch_)
### mousemove
- mousemove doesnt fire as a touch events user uses the page...
- however it does fire in [this sequence](http://www.html5rocks.com/en/mobile/touchandmouse/#toc-1) when a user taps the screen
- so maybe we can test the difference between the two?
  - [`evt.isTrusted` from DOM 4 events](https://dvcs.w3.org/hg/domcore/raw-file/tip/Overview.html#dom-event-istrusted) may be interesting. Implemented in FF, but [not in Webkit](https://bugs.webkit.org/show_bug.cgi?id=76121). isTrusted is kinda [untrusted](http://lists.w3.org/Archives/Public/www-dom/2013JanMar/0135.html) right now though
    - hypothetically it could tell the diff between the simulated mousemove and real one
  - in my tests: [`evt.which`](https://developer.mozilla.org/en-US/docs/DOM/event.which) was `0` in real mousemove and `1` in fake mousemove (part of the tap). Why? I have no idea.
  - the first time it fires, does `mousedown` fire <50ms after mousemove fired? (following the tap evt sequence) downsides galore: race condition. yucky detection, but .. might be worthwhile?
### `:hover`

`:hover` styles are never triggered by a touch user except for a brief moment during a tap.
### mouseenter / mouseleave
- They are [not implemented](http://www.quirksmode.org/dom/events/mouseover.html) in [WebKit](https://bugs.webkit.org/show_bug.cgi?id=18930)  or FF
- they were in DOM3 events but not the [dom4 events draft](https://dvcs.w3.org/hg/domcore/raw-file/tip/Overview.html)

<hr>

cc @robcolburn @roblarsen

Anyone please add any notes here that aid in the pursuit of detection of mouse users. Differences in event objects, user behavior heuristics, etc.

**Comment by jaukia** [comment]
There are a number of relevant use cases for this in interactive web apps. For example, the standard practice is to display zoom buttons on top of maps on desktop browsers but not on top of touch device maps (since they support pinch-zoom interaction). For this, detecting users with mouse would be practical.

**Comment by SlexAxton** [comment]
I think the thread goes pretty deep into this above here, but there are many devices that are both touch and mouse capable. Detecting the wrong one is deeply frustrating, and we can't guarantee the correct one (consider the millions of microsoft surface and chromebook pixel users).

I agree there are relevant use cases for knowing how a user is interacting with your app, but it cannot currently be detected ahead of time. Instead, you can adapt your application based on the actual inputs as they happen.

**Comment by patrickhlauke** [comment]
Also, remember that even on touch devices, some users don't want/can't pinch-zoom (e.g. holding mobile phone with one hand and interacting mostly with the thumb, blind user with VoiceOver/TalkBack navigating on a touchscreen device sequentially in a similar fashion to TAB/SHIFT+TAB on desktop, etc).

As @SlexAxton said, base your decisions on actual inputs (and consider that even though one moment a user may be firing touch events, the next interaction might instead come from a keyboard/mouse on multi-input devices, so make any interface/interaction changes "just in time" for the current interaction and don't then lock any other interaction methods out).

**Comment by roblarsen** [comment]
>As @SlexAxton said, base your decisions on actual inputs (and consider that even though one moment a user may be firing touch events, the next interaction might instead come from a keyboard/mouse on multi-input devices, so make any interface/interaction changes "just in time" for the current interaction and don't then lock any other interaction methods out).

I have two examples that I love to share. The one people can more readily imagine since it's been on TV ads is the case of a convertible Windows laptop like the Lenovo Yoga. It _always_ has touch capability, but fine pointer (mouse-like) control comes and goes depending on the configuration of the device. A web page can be opened in laptop mode (mouse!) and then, before anything else happens, the device can be converted to table mode (no mouse!) And then, in tablet mode, you can add a peripheral pointer (mouse or stylus) and it all goes kooky once again. 

The second is basically diabolical- I have a touchscreen laptop set up as a workstation with a second monitor. If I'm on the second monitor, I don't have touch capability, even though the OS and the browser think that I do. I often (including some very big sites that should know better) have to move sites from the second monitor to the laptop screen in order to activate controls.

**Comment by patrickhlauke** [comment]
As a side note (only because @roblarsen mentioned "fine pointer"), the current implementation in browsers of the proposed CSS4 interaction media features is borked / does not dynamically change (in Chrome at the moment, not even on page reload) https://dev.opera.com/articles/media-features/
